name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit generated images
        run: |
          git config user.name  "humaidi09"
          git config user.email "hussainahmed7p@gmail.com"
          git add -A profile-3d-contrib
          git commit -m "Update 3D contribution images" || echo "no changes"
          git push
